blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/Chalebgwa/global-transparency-dashboard/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/Chalebgwa/global-transparency-dashboard/blob/main/README.md
    about: Read the project documentation and setup guide