name: 🚀 Feature Request
description: Propose a new feature for the Global Transparency Dashboard
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a feature! Please provide details below.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what feature you'd like to see implemented
    validations:
      required: true

  - type: dropdown
    id: phase
    attributes:
      label: Project Phase
      description: Which project phase does this feature belong to?
      options:
        - Phase 1 - Discovery & Planning (Weeks 1-4)
        - Phase 2 - MVP Development (Weeks 5-16)
        - Phase 3 - Beta Launch (Weeks 17-20)
        - Phase 4 - Iteration & Polish (Weeks 21-24)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system does this affect?
      options:
        - Backend API
        - Frontend UI
        - Data Ingestion
        - CI/CD Pipeline
        - Documentation
        - Infrastructure
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define what needs to be done for this feature to be considered complete
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
        - [ ] Tests written and passing
        - [ ] Documentation updated
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.